version: "2"
services:
  influxdb:
    image: influxdb:alpine 
    container_name: "influxdb"   
    ports:
      - "8086:8086"
  chronograf:
    image: chronograf:alpine
    container_name: "chronograf"      
    ports:
      - 8888:8888
    links:
      - influxdb   
  grafana:
    image: grafana/grafana
    container_name: "grafana"      
    ports:
      - 8081:3000
    links:
      - influxdb       
  